---

- name: Create the Systemd Unit file for the apache-exporter service
  template:
    src: apache_exporter.systemd.j2
    dest: /etc/systemd/system/apache_exporter.service
    owner: root
    group: root
    mode: 0644
  notify: reload systemd and restart apache_exporter
  when: ansible_service_mgr == "systemd"

- name: Create the Upstart Unit file for the apache-exporter service
  template:
    src: apache_exporter.upstart.j2
    dest: /etc/init/apache_exporter.conf
    owner: root
    group: root
    mode: 0644
  notify: restart apache_exporter
  when: ansible_service_mgr == "upstart"

- name: Create the generic start-stop script for the apache-exporter service
  template:
    src: apache_exporter.service.j2
    dest: /etc/init.d/apache_exporter
    owner: root
    group: root
    mode: 0755
  notify: restart apache_exporter
  when: ansible_service_mgr not in [ "systemd", "upstart" ]
