---

- name: Set the Github API endpoint
  set_fact:
    _apache_exporter_github_api_url: |-
      {% if apache_exporter_release_tag == 'latest' %}
      https://api.github.com/repos/Lusitaniae/apache_exporter/releases/latest
      {% else %}
      https://api.github.com/repos/Lusitaniae/apache_exporter/releases/tags/{{ apache_exporter_release_tag }}
      {% endif %}

- name: Set the Github API token
  set_fact:
    _apache_exporter_github_api_token: "{{ lookup('env', 'GITHUB_API_TOKEN') }}"

- name: Fetch the apache-exporter release information from Github
  uri:
    url: "{{ _apache_exporter_github_api_url }}"
    method: GET
    headers:
      Authorization: "{% if _apache_exporter_github_api_token %}token {{ _apache_exporter_github_api_token }}{% endif %}"
  check_mode: no
  register: _apache_exporter_github_release
  until: |
    'status' in _apache_exporter_github_release
      and _apache_exporter_github_release['status'] == 200
  retries: 5
  delay: 15

- name: Get the tag of the latest apache-exporter Github release
  set_fact:
    apache_exporter_release_tag: "{{ _apache_exporter_github_release['json'] | json_query('tag_name') }}"
  when: apache_exporter_release_tag == "latest"

- name: Set the Github download URL for the apache-exporter release
  set_fact:
    apache_exporter_release_url: "{{ _apache_exporter_github_release['json'] | json_query(_apache_exporter_release_asset_url_query) }}"
  vars:
    _apache_exporter_release_asset_url_query: "assets[?name=='{{ hostvars[inventory_hostname] | apache_exporter_release_build(apache_exporter_release_tag) }}.tar.gz'] | [0].browser_download_url"  # noqa 204
